permissions:
  contents: read

on:
  workflow_call:
    # TODO: add crates input?
    inputs:
      rust:
        required: false
        type: string
        default: nightly-2022-11-16
      args:
        required: false
        type: string

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  check-external-types:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup toolchain add ${{ inputs.rust }} --no-self-update --profile minimal && rustup default ${{ inputs.rust }}
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-check-external-types@0.1.6
      - run: cargo check-external-types --all-features --config .external-types.toml ${{ inputs.args }}
