permissions:
  contents: read

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@shellcheck
      - uses: taiki-e/install-action@shfmt
      - run: tools/tidy.sh
        if: always()
